### ISSUE TITLE
New user trying docker build without success

### ISSUE THREAD

**Issue by mannp** [ThomasTJdev/nim_websitecreator#100]
### Bug Short Description:

Spent a good part of the day trying to get the docker build working without success.

Using docker I am getting issues with nim nor git in the searchable path and no nimwc executable created, so web admin and site not accessible.

Wondered if it needed an update or I was missing something? 

Is the docker build an out of the box experience or still needs the install actions to be completed to work?

Thanks in advance

## Version
```
    5.0.0
```

**Comment by juancarlospaco** [comment]
The `Dockerfile` and `Vagrantfile` are kinda templates to get you started, 
so probably customizing it for your use case and configurations on top is needed.

Having said that, we want to keep improving, to the point it will be more useful out of the box,
but I can not guarantee it will always work without changes, at least no as it is now.

This issue can be open so we track it here.

**Comment by mannp** [comment]
I see okay thanks.

I am all for configuring for my use case and tweaking for what I need, I guess I was hoping for a minimal scenario that I could change.

My first time with nim so also a challenge :)

Would it be possible for someone who knows nim and nimwc to take the docker for a spin and point me in the direction of the likely issues please?

**Comment by juancarlospaco** [comment]
Yes, theres a [Videotutorial from cero step-by-step that happens to include compiling without Firejail.](https://youtu.be/3R1l4Ha0tDI)
:slightly_smiling_face:

**Comment by mannp** [comment]
Okay thanks, will try.

One obvious issue is **/root/**nim_websitecreator/nimwc.nim actually appears to be /nim_websitecreator/nimwc.nim

**Comment by juancarlospaco** [comment]
Fixed by https://github.com/ThomasTJdev/nim_websitecreator/pull/101
