### ISSUE TITLE
Wikipedia

### ISSUE THREAD

**Issue by juancarlospaco** [ThomasTJdev/nim_websitecreator#108]
- Write a Wikipedia page about NimWC, as complete as possible but following Wikipedia best practices.

Other examples of Wiki articles:

- Nim https://en.wikipedia.org/wiki/Nim_(programming_language)
- Bottle (single-file tiny Python web framework) https://en.wikipedia.org/wiki/Bottle_(web_framework)

Questions:

- Can we crossreference Nim article?.

**Comment by juancarlospaco** [comment]
WIP: https://en.wikipedia.org/wiki/User:Juancarlospaco/sandbox :thinking:

**Comment by ThomasTJdev** [comment]
Check update: https://en.wikipedia.org/wiki/User:Juancarlospaco/sandbox

**Comment by juancarlospaco** [comment]
Live: https://en.wikipedia.org/wiki/NimWC
:tada: :+1: :rocket:

**Comment by ThomasTJdev** [comment]
> Live: https://en.wikipedia.org/wiki/NimWC

Down now..

**Comment by juancarlospaco** [comment]
Oh, we tried... I will check
:crying_cat_face:
