### ISSUE TITLE
I want to understand the PPL license

### ISSUE THREAD

**Issue by csajedi** [ThomasTJdev/nim_websitecreator#111]
Hi,

I want to use Nim WC for my professional landing page and blog, but I am a for-profit LLC. I am the only employee, and have never made a profit- but I hope to change that one day. Can you validate my thinking that as long as my LLC is never owned by non-workers (like through an IPO or VC) I will be fine to use it for my blog (even if I find revenue eventually)? 
I'd of course want to contribute back to the project as time permits.

**Comment by juancarlospaco** [comment]
https://tldrlegal.com/license/peer-production-license

Basically is like MIT, very similar, in fact it tries to help you on the use case you are describing.

It exactly wants to help you work and revenue and all the things you need for the project to be alive!.
Even more, thats the reason the framework includes like an App Store for your custom libraries and pages.
Notice the Store is backed by Git, so it can even be used from Private or self-Hosted Git.

The change is that it helps you if someday mega-corporation wants to just take all your code,
just rename it, and sell it, without contributing anything back, not even a "thank you",
it already happened to MongoDB (was GPL) which Amazon just renamed and sells as Cloud.

I can provide links but I think most devs already know whats MongoDB or Amazon.
Besides you can read everything here: 
https://github.com/ThomasTJdev/nim_websitecreator/issues/53#issue-413664003

For comparison MIT https://tldrlegal.com/license/mit-license MIT is also similar to Apache2.
Let me know if thats enought explanation, or I can extend it even more, no problem :slightly_smiling_face:

**Comment by csajedi** [comment]
@juancarlospaco thanks for the writeup. I expected that to be largely the case - but I'm not a lawyer and don't want to do anything egregiously illegal in my quest to have a landing page with room to grow. I saw the PPL license and actually got quite excited - seems like an interesting development in the space of software intended for use by the general public without the possibility of enclosure. If I were to contribute fixes/code back to the project I'd certainly be bummed if Amazon snapped it up with some rebranding. I support your decision and read issue #53 before making this post.
