### ISSUE TITLE
AutoInstall: Copy Alpines method

### ISSUE THREAD

**Issue by juancarlospaco** [ThomasTJdev/nim_websitecreator#121]
https://github.com/alpinelinux/alpine-chroot-install#usage

They put a Checksum on the autoinstall bash command.
We can make that with a SHA512sum for the AutoInstall.

**Comment by juancarlospaco** [comment]
Remember to Update the SHA sum when updating the file.
:slightly_smiling_face:

**Comment by ThomasTJdev** [comment]
> Remember to Update the SHA sum when updating the file.
> 🙂

We need a check for that in our future-test suite ;)
