### ISSUE TITLE
BCrypt --> Argon2

### ISSUE THREAD

**Issue by juancarlospaco** [ThomasTJdev/nim_websitecreator#124]
https://github.com/Ahrotahn/argon2#detailed :grey_question: :thinking:

**Comment by ThomasTJdev** [comment]
Looks good, and Argon2 could be a good replacement for bCrypt. But I'm not a fan of 
```
Argon2 makes use of multiple threads, so the --threads:on flag must be used when compiling your project.
```

Have you experimented with it?

**Comment by juancarlospaco** [comment]
I've read the source is very small ~100 line wrapper, very direct wrapper wont do anything for itself,
it directly calls Argon2, and it seems Argon2 itself needs threads for everything.

Maybe we can continue using BCrypt, is the second best algo anyways.
