### ISSUE TITLE
Update Repo Description

### ISSUE THREAD

**Issue by juancarlospaco** [ThomasTJdev/nim_websitecreator#125]
The Repo Description reads something like `Website creation automated with Nim...`,
I have seen several people not understanding whats NimWC, some think its an Automation Tool, etc.

I think the Repo Description needs to be changed to something like:
`Nim FullStack Web Framework` or similar.

That is probably what most people search GitHub and Google for.
And let users discover the rest of the features from the Documentation.
I can not change that, so ping @ThomasTJdev 

:slightly_smiling_face:

**Comment by ThomasTJdev** [comment]
Updated - OK?

**Comment by juancarlospaco** [comment]
Awesome :grey_exclamation:
