### ISSUE TITLE
Use Github Wiki

### ISSUE THREAD

**Issue by ThomasTJdev** [ThomasTJdev/nim_websitecreator#126]
I would like to use the Github Wiki to provide basic information, to get NimWC up and running. Something like:

https://github.com/ThomasTJdev/nim_homeassistant/wiki/Nginx-&-SSL

https://github.com/ThomasTJdev/nim_homeassistant/wiki/Autorun-on-boot

What do you think @juancarlospaco ?

**Comment by juancarlospaco** [comment]
Do it. :+1:
