### ISSUE TITLE
Error: 'getPluginsPath' can have side effects [Nim v1.2.0]

### ISSUE THREAD

**Issue by ThomasTJdev** [ThomasTJdev/nim_websitecreator#129]
Building with Nim version 1.2.0 fails. I think we need to roll back [func getPluginPath](https://github.com/ThomasTJdev/nim_websitecreator/blame/master/nimwcpkg/nimwc_main.nim#L39) to a `proc` due to the strict side effects check. @juancarlospaco, can you take a quick test spin?

## Fail
```
/home/cxwiki/nimwcpkg/nimwc_main.nim(21, 35) Warning: WebP is disabled, no image optimizations possible. [User]
/home/cxwiki/nimwcpkg/nimwc_main.nim(24, 39) Warning: Firejail is disabled, running unsecure. [User]
/home/cxwiki/nimwcpkg/nimwc_main.nim(39, 6) Error: 'getPluginsPath' can have side effects
```

## Code
https://github.com/ThomasTJdev/nim_websitecreator/blob/d22fc86aa934ee3286b8fa5c4c046f3c90fc4bbe/nimwcpkg/nimwc_main.nim#L39-L66

**Comment by juancarlospaco** [comment]
I agree, you are right.
