### ISSUE TITLE
Require newer `recaptcha`

### ISSUE THREAD

**Issue by narimiran** [ThomasTJdev/nim_websitecreator#130]
Currently in your `nimwc.nimble` you have `requires "recaptcha >= 1.0.2"`, and nimble seems to pick up `recaptcha` at exactly that version.
The problem lies with the fact that recaptcha v1.0.2 doesn't work with the latest Nim (see https://github.com/euantorano/recaptcha.nim/pull/2).

The solution for this is bumping the required version:
`requires "recaptcha >= 1.0.3"`

**Comment by ThomasTJdev** [comment]
Thanks @narimiran - good catch. I made a [PR](https://github.com/euantorano/recaptcha.nim/pull/6) at recaptcha 12 days ago, so I had the updated version while testing. I'll update `nimwc.nimble` and publish a new release.

Thoughts:
Maybe we should have a test, which changes the requirements from `>=` to `==`. Maybe a Nimble-package...
