### ISSUE TITLE
SYS_getrandom undefined

### ISSUE THREAD

**Issue by cvanelteren** [ThomasTJdev/nim_websitecreator#142]
Hi,
I was trying out your package and ran into some compilations issues. I had some looking around and found a related error call ([here](https://www.google.com/search?client=firefox-b-d&q=+readBytesX60gensym0_+%3D+syscall%28SYS_getrandom%2C+%28%28void*%29+%28%28%26dest%5Bresult%5D%29%29%29%2C+%28%28int%29+%28%28NI%29%28TM__sT0fWggTrXhnxQ79bl9a8nHg_2%29%29%29%2C+%28%28unsigned+int%29+0%29%29%3B)), but I am not running the mentioned kernel there (<3.17 vs 5.19.4) do you perhaps know how to solve this underlying issue? 

Detail:
nim 1.6.4

<details>
<summary> output </summary>

```
/home/casper/.cache/nim/nimwc_main_r/stdlib_sysrand.nim.c: In function 'urandomInternalImpl__stdZsysrand_17':
/home/casper/.cache/nim/nimwc_main_r/stdlib_sysrand.nim.c:61:56: error: 'SYS_getrandom' undeclared (first use in this function); did you mean 'SYS_getuid'?
   61 |                         readBytesX60gensym0_ = syscall(SYS_getrandom, ((void*) ((&dest[result]))), ((int) ((NI)(TM__sT0fWggTrXhnxQ79bl9a8nHg_2))), ((unsigned int) 0));
      |                                                        ^~~~~~~~~~~~~
      |                                                        SYS_getuid
/home/casper/.cache/nim/nimwc_main_r/stdlib_sysrand.nim.c:61:56: note: each undeclared identifier is reported only once for each function it appears in
Error: execution of an external compiler program 'gcc -c  -w -fmax-errors=3 -O3 -fno-strict-aliasing -fno-ident   -I/home/casper/.choosenim/toolchains/nim-1.6.4/lib -I/home/casper/projects/nimwc/nimwcpkg -o /home/casper/.cache/nim/nimwc_main_r/stdlib_sysrand.nim.c.o /home/casper/.cache/nim/nimwc_main_r/stdlib_sysrand.nim.c' failed with exit code: 1

```
</details>

**Comment by ThomasTJdev** [comment]
Hi @cvanelteren 

That is a new one to me. Could you try adding `-d:nimNoGetRandom` to [nimwc.nim.cfg](https://github.com/ThomasTJdev/nim_websitecreator/blob/25da50c01a15338336d9a624c729f8f51c9697a0/nimwc.nim.cfg) before compiling?

**Comment by ThomasTJdev** [comment]
The problem is coming from this:
https://github.com/ThomasTJdev/nim_websitecreator/blob/25da50c01a15338336d9a624c729f8f51c9697a0/nimwcpkg/passwords/passwords.nim
```
let useUrandom = urandom.open("/dev/urandom")
```

You could try setting that to false. That will affect the `makeSalt()` procedure to **not** using urandom.

**Comment by cvanelteren** [comment]
Unfortunately, same error when setting it to false. It seems like it is not an issue with `nimwc`, the error originates from the stdlib it seems.

**Comment by cvanelteren** [comment]
This automagically fixed itself, closed!

**Comment by ThomasTJdev** [comment]
Perfect 😃

tor. 29. sep. 2022 20.47 skrev Casper van Elteren ***@***.***
