### ISSUE TITLE
More Explicit Login on Demo

### ISSUE THREAD

**Issue by juancarlospaco** [ThomasTJdev/nim_websitecreator#17]
https://nimwc.org/login

It only says *"use the test user"*, Ive tried:
- `test`
- `test@test`
- `demo`
- `demo@demo`
- All of the above with and without `.com`

Honestly I dont know whats the user and password on the Demo.
Maybe just be more explicit, add on the index page something like:

**USER:** `test@test.com`
**PASS:** `test`

:thinking:

**Comment by ThomasTJdev** [comment]
Good catch! Your bruteforce actually resulted in the correct user and pass ;-) (test@test.com/test) - but I forgot to compile with `-d:demo`, which would show the username and password and allowing you to login with the demouser.

I will fix it later or on saturday. Thanks!

https://github.com/ThomasTJdev/nim_websitecreator/blob/master/nimwcpkg/tmpl/user.tmpl#L30-L37

https://github.com/ThomasTJdev/nim_websitecreator/blob/master/nimwcpkg/nimwc_main.nim#L382-L384

**Comment by ThomasTJdev** [comment]
Compiled with `-d:demo`:

https://nimwc.org/login
