### ISSUE TITLE
nimble init like for nimwc

### ISSUE THREAD

**Issue by juancarlospaco** [ThomasTJdev/nim_websitecreator#20]
Have a command like `nimble init` for `nimwc` to create this Plugin skeleton https://github.com/ThomasTJdev/nimwc_plugins#plugin-structure

**Comment by ThomasTJdev** [comment]
Note to self - js_ and css_private is not required:
https://github.com/ThomasTJdev/nim_websitecreator/blob/master/nimwcpkg/nimwc_main.nim#L183-L184
https://github.com/ThomasTJdev/nim_websitecreator/blob/master/nimwcpkg/nimwc_main.nim#L247-L248

**Comment by ThomasTJdev** [comment]
4b0d113790cb1b986046e651f5af46e77d68fc48

```
nimwc --initplugin
```
