### ISSUE TITLE
How to Remove Default Bootstrap

### ISSUE THREAD

**Issue by juancarlospaco** [ThomasTJdev/nim_websitecreator#22]
I created https://github.com/juancarlospaco/nimwc_bulma#nimwc_bulma

https://bulma.io

Bulma is similar to Bootstrap, but uses **No JavaScript** at all, which is awesome for Nim Web Apps, since Nim can work on the Frontend replacing JavaScript (Karax, etc).

I can not find on the Documentation how to Remove the default Bootstrap 4 thats added by default.

Bootstrap loads from a CDN thats not always wanted nor the best way.

Good thing to consider is, **we really need Bootstrap by default** :question: 

We should ship a basic tiny Framework-less CSS.

Move out Bootstrap as a Plugin.

So user can choose several CSS Frameworks, like Bootstrap or Bulma.

Feel free to Review my Plugin too, I can not really test it because I can not remove Bootstrap.

**Comment by ThomasTJdev** [comment]
I haven't seen Bulma before - it looks nice! I'm in for removing jQuery and Bootstrap as standard elements and providing a slimmer solution. I decided to provide them as standard so people, who just wanted a blog, didn't have to fiddle with <script> and <style> tags. I think we need to ship NimWC with some kind of standard CSS and JS to get people started - maybe the solution is to make it easier/more visible on how to get rid of it?

You can remove the Bootstrap links by:
1) Go to "Settings"
2) Choose "Edit HTML" (maybe another name is needed?
3) Remove Bootstrap from "HTML <head>"

I'll checkout your plugin in the next days.

**Comment by juancarlospaco** [comment]
Replace Bootstrap with Bulma ?. Its a lot more lightweight.
Move Bootstrap as a Plugin instead.

**Comment by ThomasTJdev** [comment]
I'm in a limbo..

**Bulma** = 22,5kb
**jQuery & Bootstrap** = 69,5kb

This makes a dif on 47kb.

I assume that the majority of users are more comfortable with Bootstrap, whereas I like to keep it in the standard data. But for the settings (`genMainAdmin()`) I'm open for changing. If we do change it, I think we should get rid of both jQuery and Boostrap. This includes some work on:
- Core JS
- Profil picture editor
- Summenote
- GrapeJS
- Codemirror
- Core CSS

Futhermore, we need might need to implement some kind of check, so that 2 plugins does not load jQuery.

Is it a task, you are up for?

**Comment by juancarlospaco** [comment]
Bulma is very popular the far you go from JavaScript / PHP, eg seen lots of Haskell, Go, etc people use it.
Is easy to learn and has nice docs.
Bulma does Not block you from loading Jquery, it doesnt care, if you need to load JQuery for a component just do it.
Bootstrap popularity is high, JQuery is kinda dropping.
But I think Nim being a lang that can run on the Frontend, is different use case.

I have a fork that runs Bulma already.

I did not remove the Bootstrap classes from the HTML,
so if the user switches to Bootstrap it should work with tiny to no changes.

**Comment by juancarlospaco** [comment]
https://github.com/ThomasTJdev/nim_websitecreator/compare/master...juancarlospaco:master
Should I make a WIP  PR?
:smile_cat:

**Comment by ThomasTJdev** [comment]
Please yes!! Great work - I really like the cleanup! :+1: 

**nimble.nim** => Do we really need 0.19.0?
**HTML** => 
* Regarding your comment https://github.com/ThomasTJdev/nim_websitecreator/issues/23#issuecomment-429326459 about a quick start template without too much branding and wasted cleanup time - I like that approach. What about having a simple bareback template, which is loaded on the first run, when the DB is created. No example blogs and NimWC branding. It could consists of relevant headers and a frontpage with a simple guide on how to get startet with either Bulma, Bootstrap or no framework (where to access settings etc.)? If the user would like more inspiration, the `--insertdata` arg can be used to load the NimWC branding site.

**JS** => All the JS currently depends on jQuery. Are you already working on it? Should we split the work? Or should I take the first run at it? Let me know how you would like to proceed.

*I'm pretty impressed about all my whitspaces you caught :)*

**Comment by juancarlospaco** [comment]
`0.18.1` is the same as `0.19.0`, I dont want to start adding `{.deprecated.}` on NimWC :neutral_face: 

If the Editors, etc Need JQuery, it will be loaded, loading JQuery does not break Bulma.

Nice to create a more lightweight starting template with no brandings.

Too bad Nim yet dont have a big ORM like Djangos, I would love to create one someday.

I didnt catch whitespaces, Editor does, I use Atom and [my custom Spacemacs](https://github.com/juancarlospaco/spacemacs-nim-python#spacemacs-nim-python).
I dont use VS Code after discovered is Legal trolling (says is open source but EULA reverts it back to propietary)

I would send PR.

**Comment by ThomasTJdev** [comment]
Closed d708a0b2b8d358f41af7091e2a02862d9a5862b3

Thank you for the PR!
