### ISSUE TITLE
Include tutorial and guidance on nimwc.org 

### ISSUE THREAD

**Issue by ThomasTJdev** [ThomasTJdev/nim_websitecreator#23]
Include installation, configuration, etc. information on nimwc.org.

Set standard data to include this information, so user has access to it, when using arg `--insertdata`.

**Ref:**
- How to Remove Default Bootstrap #22 
- Idea: Add optional minimal favicon.ico #21

**Comment by juancarlospaco** [comment]
I dont know if you need a new parameter for that, just with the Demo settings will be Ok.
The new information added (can double as Documentation) plus the branding when on Demo mode.

---

For an opinion/feedback, I think that the default site when Not on Demo mode is kinda too "Branded".

I mean if I am running it locally I am already sold to it, I am already liking it, 
but imagine that I have an hour to make a basic site, 
if I have to take ~20 minutes or more De-Branding it, to start to work thats not good, 
can move users away, or they can use a template from internet instead,
that can include removing some branding, like some images and wording when not on Demo mode.

**Comment by ThomasTJdev** [comment]
Closed d708a0b2b8d358f41af7091e2a02862d9a5862b3
