### ISSUE TITLE
Handle failure in recompiling gracefully

### ISSUE THREAD

**Issue by ThomasTJdev** [ThomasTJdev/nim_websitecreator#25]
If recompiling due enabling/disabling a plugin fails alert the user (with fault code?).

https://github.com/ThomasTJdev/nim_websitecreator/blob/c37a01370aaa80780c3dbe14c1ae323f6f9f2bbf/nimwcpkg/resources/web/routes.nim#L80-L101

https://github.com/ThomasTJdev/nim_websitecreator/blob/master/nimwcpkg/nimwc_main.nim#L331-L334

**Comment by juancarlospaco** [comment]
This is kinda handled by the Log Viewer, I can easily see the errors on the Logs. Fixed :grey_question: 
:smile:

**Comment by ThomasTJdev** [comment]
The log function is perfect
