### ISSUE TITLE
Arg to minify CSS and JS

### ISSUE THREAD

**Issue by ThomasTJdev** [ThomasTJdev/nim_websitecreator#28]
Minify the CSS and JS. Use script.min.js and style.min.css.

(Rename js.js to script.js)

**Comment by juancarlospaco** [comment]
https://github.com/juancarlospaco/nim-css-html-minify#css-html-minify

**Comment by ThomasTJdev** [comment]
Is it production ready? Cause then we shall implement it :) !

Do you have a JS minifier in pipeline?

**Comment by juancarlospaco** [comment]
I dont know if this should be inside nimwc, most CSS framework provide minified versions,
the only minifiers use NodeJS and Java, thats kind of moving the user away from Nim,
JavaScript syntax change very quickly and can get really weird,
most users will do this aside nimwc anyways.
:thinking:

**Comment by ThomasTJdev** [comment]
You right. I personally use https://github.com/tdewolff/minify in an integrated solution for my website. Let's close this.
