### ISSUE TITLE
`nimble install nimwc` fails (4.0.5)

### ISSUE THREAD

**Issue by ThomasTJdev** [ThomasTJdev/nim_websitecreator#29]
When running `nimble install` locally from a git clone there's no problem, but when running `nimble install` and fetching through Nimble install fails:
```nim
Installing nimwc@4.0.5
   Building nimwc/nimwc using c backend
    Prompt: Build failed for 'nimwc@4.0.5', would you like to try installing 'nimwc@#head' (latest unstable)? [y/N]
```

**Comment by juancarlospaco** [comment]
https://github.com/ThomasTJdev/nim_websitecreator/blob/master/nimwc.nim#L87
Fails to read the Version from the *.nimble file, because nimble install seems to delete it ?.

**Comment by juancarlospaco** [comment]
Fixed permanently, I hope. :smile:
