### ISSUE TITLE
URL has wrong format after been formatted

### ISSUE THREAD

**Issue by ThomasTJdev** [ThomasTJdev/nim_websitecreator#35]
Ref.: b0b4100

I ran into trouble.. Problem: **My URL's are ugly**

I am naming my blog posts:
https://website.com/blog/YYYY/MM/DD/name

But this now returns the following in the addressbar in Chrome when accessing the blogpost.
https://website.com/blog/2018%2F11%2F16%2Fmy-normal-name

**Comment by juancarlospaco** [comment]
Oh no, feel free to revert the change then... :slightly_smiling_face:

**Comment by ThomasTJdev** [comment]
Or we could keep the change and just replace `%2F` to `/`? Is there any other characters we need in the URL, which should be converted?

**Comment by juancarlospaco** [comment]
Maybe you can have a `replacements` on the config or settings then use https://nim-lang.org/docs/strutils.html#multiReplace%2Cstring%2Cvarargs%5B%5D

**Comment by ThomasTJdev** [comment]
Fixed with simple replace 081e83060def21fcd2183c1c58c29145b96393f2

Multireplace and custom params is not implemented. If it's going to be implemented, it would be nice to keep it in the admin panel.
