### ISSUE TITLE
Count downloads of files

### ISSUE THREAD

**Issue by ThomasTJdev** [ThomasTJdev/nim_websitecreator#45]
## Proposal

1) Currently files are uploaded to the folder images - should this be splitted or renamed to files? It's just ugly to serve a PDF file from a folder names *images*

2) Each time a file is served to a user, `sendFile()`, `inc(1)` to table `file.downloadCount`. This will allow to the user to have statistics.

**Comment by juancarlospaco** [comment]
Rename `images` to `files`.

Theres no tables for files, you mean to add one, I agree.

I think table and folder should have the same name, so `files` for both.

**Comment by ThomasTJdev** [comment]
I agree :+1:

**Comment by ThomasTJdev** [comment]
Fixed in PR #39
