### ISSUE TITLE
Material Design

### ISSUE THREAD

**Issue by juancarlospaco** [ThomasTJdev/nim_websitecreator#46]
https://jenil.github.io/bulmaswatch/materia/

is just adding 1 line to HTML.
Or we can make the user choose the theme, it only needs to change the URL, 
we can have all URLs on a `const` like a `Table`

**Comment by ThomasTJdev** [comment]
1) Is it different Bulma themes?
2) Do you plan to use it only on "admin pages" or on "public & admin pages"?

**Comment by juancarlospaco** [comment]
Yes, Bulma themes.
Use it everywhere when choosed.

**Comment by juancarlospaco** [comment]
Fix on https://github.com/ThomasTJdev/nim_websitecreator/pull/74#issue-259793182

**Comment by juancarlospaco** [comment]
https://github.com/ThomasTJdev/nim_websitecreator/pull/74#issuecomment-494920539
