### ISSUE TITLE
Freelancers tool

### ISSUE THREAD

**Issue by juancarlospaco** [ThomasTJdev/nim_websitecreator#47]
https://github.com/kleampa/not-paid#client-did-not-pay
https://github.com/kleampa/not-paid/blob/master/not-paid.js

I like the idea, is a cool feature, can be super easy to implement as server-side No-JS Admin controlled feature, good tool to attract Freelancer users.

**Comment by ThomasTJdev** [comment]
I don't think I understand the usage in NimWC. Can you give an example?
