### ISSUE TITLE
Pure CSS Native Smooth Scroll

### ISSUE THREAD

**Issue by juancarlospaco** [ThomasTJdev/nim_websitecreator#48]
https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-behavior
Implement Pure CSS Native Smooth Scroll by default.
Its just 1 Line of CSS. Implement globally for all by default.

**Comment by ThomasTJdev** [comment]
Interesting. We just need to be aware, that it has no support for Safari.

Are you thinking about removing: 
https://github.com/ThomasTJdev/nim_websitecreator/blob/master/public/js/js.js#L34-L45

**Comment by ThomasTJdev** [comment]
Hmm, iPhone users tends to like smooth scrolling and animations. I don't wont to miss out on them.. We need to ensure, that people with Apple products also get's a nice experience. If we are going to change it now, I could of course just insert the current JS-snippet into the JS-custom file.

**Comment by juancarlospaco** [comment]
You prefer to keep it with the JS solution :grey_question: 
I have no problem, just seen the CSS feature and think it worth trying, mainly because on the worse case it wont work is just vanilla scroll anyways.
:slightly_smiling_face:

**Comment by juancarlospaco** [comment]
I tried this, it has a problem `This property specified on the body element will not propagate`.
It does not propagate, it does not get Inherited at all, theres no way to set it globally, 
user must set it individually if want to use it, is different than JS one.

Closing because Wont Fix.
