### ISSUE TITLE
Remove bootstrap class from admin pages

### ISSUE THREAD

**Issue by ThomasTJdev** [ThomasTJdev/nim_websitecreator#49]
Remove all bootstrap class from admin pages. Admin pages uses bulma.

**Comment by juancarlospaco** [comment]
It seems you liked Bulma. What about dropping Bootstrap everywhere.

Id rater support Spectre than Bootstrap:
- https://picturepan2.github.io/spectre/experimentals.html
- https://picturepan2.github.io/spectre/experimentals/viewer-360.html
- https://picturepan2.github.io/spectre/experimentals/parallax.html
- https://picturepan2.github.io/spectre/experimentals/carousels.html
- 10Kb, No JS.

**Comment by ThomasTJdev** [comment]
I'm in for dropping Bootstrap on all "browser-backend", but I would like to have the standard-data available with bootstrap. **OR** I should just move that to a plugin, e.g. the template plugin?

Would you drop Bulma for Spectre?

**Comment by juancarlospaco** [comment]
Ok, no problem. Not dropping Bulma for Spectre.
It is really good if you try it, only thing I found it missing is Themes yet.
