### ISSUE TITLE
/settings/edit "See Templates" button cleanout

### ISSUE THREAD

**Issue by juancarlospaco** [ThomasTJdev/nim_websitecreator#52]
http://127.0.0.1:7000/settings/edit has a "See Templates" button (when not Demo),
when clicked shows the same text repeated twice but read-only and not highlighted.

Whats that for @ThomasTJdev :grey_question: It doesnt seem to improve the UX too much, can we remove it :grey_question: 
:thinking:

**Comment by ThomasTJdev** [comment]
Ohh that's a mistake. I tried to let the user enable/disable firejail and unsplash from the browser and I needed a page for it. I discarded the idea, but I forgot to remove the button.

**Comment by juancarlospaco** [comment]
Fixed on https://github.com/ThomasTJdev/nim_websitecreator/pull/39

**Comment by ThomasTJdev** [comment]
The lines below they are not used, when the button is removed. I think my answer above was misleading and wrong. The template button was to show *how to user could insert data* - so if the user messed up the code, he could just copy'paste the template code in.

https://github.com/ThomasTJdev/nim_websitecreator/blob/634fd67d3f90ec275632f00267c2bc82f398f520/nimwcpkg/tmpl/settings.tmpl#L170
https://github.com/ThomasTJdev/nim_websitecreator/blob/634fd67d3f90ec275632f00267c2bc82f398f520/nimwcpkg/tmpl/settings.tmpl#L176
https://github.com/ThomasTJdev/nim_websitecreator/blob/634fd67d3f90ec275632f00267c2bc82f398f520/nimwcpkg/tmpl/settings.tmpl#L182
