### ISSUE TITLE
Relicense tinkering

### ISSUE THREAD

**Issue by juancarlospaco** [ThomasTJdev/nim_websitecreator#53]
Consider Relicensing from GPL, upcoming V5 and being 2 core devs is a good opportunity. 
This is an open discussion.

**Proposed options:**
- MIT like [Nim](https://github.com/nim-lang/Nim/blob/devel/copying.txt) :arrow_right:  https://tldrlegal.com/license/mit-license
- [PPL](http://wiki.p2pfoundation.net/Peer_Production_License#Description) :arrow_right: https://tldrlegal.com/license/peer-production-license

**Criticism for GPL3:**
- Viral by design.
- Software can be Patented.
- Source must be included with Binary.
- If the core framework is GPL everything else should be GPL.
- https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)

**MIT description:**
A short, permissive software license. 
Basically, you can do whatever you want as long as you include the original copyright and license notice in any copy of the software/source.
It may be harder or impossible to economically sustain in the long run compared to PPL.

**PPL description:**
The Peer Production License is derived from the Creative Commons ‘Attribution-NonCommercial-ShareAlike’ license. 
However unlike CC-BY-NC-SA, PPL demands reciprocation (whether monetary or otherwise) from non-contributing commercial entities (AKA Big Corporations) whilst fostering "Open Cooperativism" on open source community. 
Enables capital-accumulation for commons-oriented open peer production models 
(Freelancers, Cooperatives, Independent Workers, Remote Workers, Small Businesses, etc).
Is a relatively new license, and a lot of people dont know it yet, but has a lot of potential for the future (much like Nim itself). Nim is older than PPL.

**The Problem PPL solves:**
How to ensure that the project doesn’t just become free development for private corporations? 

The Peer Production License is a reciprocity-based license by which commons are freely accessible to those who contribute to create them, 
while third party non-contributing entities profiting from these commons can be charged a license fee to sustain the project in the long run.
It helps protect digital, natural and biological resources ,
such as software, hardware, designs, seeds, plants, ancestral knowledge and more goods against the danger of privatization, while enable and incentive their wider use.
Developers can not earn a living from exclusivity of "intellectual property",
neither Copyleft licenses like the GPL, nor Copyright like Proprietary, can solve, 
then PPL aims to create 'ethical' entrepreneurial coalitions, solidarity economy, 
and similar real world best practices (the idea comes from open source software cooperatives).
As seen it covers beyond software as compared to MIT and older licenses.

**My view:**
I really like PPL, is like a more real-world MIT, 
where people needs to pay rent but at the same time loves open source, 
where big corporations may just rename your project when it becomes popular and sell it without giving back a cent.
Having said that, I also consider MIT to be pretty good, and have no problem on using it too.

What do you think @ThomasTJdev :grey_question:

**Comment by ThomasTJdev** [comment]
The PPL is new to me, but it sounds really good. I'm well aware of the problems with GPL, but at the time, I thought it was my best option, to obtain the same possibilities as the new PPL.

## 1
Have you found any examples on other software using the PPL?

## 2
I'm having a hard to time understanding this paragraph from the PPL:

Who are the **worker-owners** - is it us? Is it the business developing?
```
c. You may exercise the rights granted in Section 3 for commercial purposes only if:
  i. You are a worker-owned business or worker-owned collective; and
  ii. all financial gain, surplus, profits and benefits produced by the business or collective are distributed among the worker-owners
```

## 3
Yardanico has contributed with some PR's. IANAL so I don't know, if he has a vote in this?
https://github.com/ThomasTJdev/nim_websitecreator/pull/5
https://github.com/ThomasTJdev/nim_websitecreator/pull/6
https://github.com/ThomasTJdev/nim_websitecreator/pull/7
https://github.com/ThomasTJdev/nim_websitecreator/pull/8

**Comment by juancarlospaco** [comment]
### 1
I dont know, I never found a search engine that indexes licenses properly, 
even if you can search for `BSD` theres 0-clause BSD, 1-clause BSD, 2-clause BSD, 3-clause BSD, 4-clause BSD, 5-clause BSD, and they are different licenses (of the same family).
Some are here but barely as an example http://wiki.p2pfoundation.net/Peer_Production_License#Examples:_Directory_of_Adopters
Most people tends to just go with whatever the Git page chooses as default sadly.

### 2
Worker or owners is us. We work on the project.
Business or collective is the development. We are a collective of software development.
The wording is because its meant to work for other stuff like open hardware, etc.

### 3
If he has Repo push permissions, Yes.
If he has No Repo push permissions, No.
Technically you do the merge on his behalf.
Hes a cool person anyways I dont think he will make drama.

:slightly_smiling_face:

**Comment by juancarlospaco** [comment]
Fixed on https://github.com/ThomasTJdev/nim_websitecreator/pull/39

**Comment by ThomasTJdev** [comment]
License in nimwc.nimble and nimble packages are not the same:

https://forum.nim-lang.org/t/4703
"... The license for the nimwc module is incorrectly identified as "GPLv3" in nimble metadata, but it's actually the PPL as well. ..."

**Comment by juancarlospaco** [comment]
He just a Troll, he wastes time on **Trolling and Boycotting all Projects on GitHub**,
he dont even code Nim, I think Nim community is smarter than than that.

![troll0](https://user-images.githubusercontent.com/1189414/54060193-8e71a800-41da-11e9-9d3f-4015ec853a8f.png)

![troll3](https://user-images.githubusercontent.com/1189414/54060376-41da9c80-41db-11e9-8560-a27023797585.png)

![troll1](https://user-images.githubusercontent.com/1189414/54060382-456e2380-41db-11e9-9163-53ca8b55f133.png)

---


- Going back to the point, is that a Cache somewhere :grey_question: I search on my IDE and cant find "GPL" :grey_question: Feel free to push the Fix directly if you know what it is.
:slightly_smiling_face:

**Comment by ThomasTJdev** [comment]
It was in the nimble package.json - pushed a PR.

**Comment by juancarlospaco** [comment]
For Historical reasons:

IBM steals all Flickr user photos to train and sell Proprietary IA,
without permission from Flickr nor the users, including user classification by Race and Skin color,
uses may include facial recognition of "potential" threats (airports, borders, etc). Ok by its License.
https://www.theverge.com/2019/3/12/18262646/ibm-didnt-inform-people-when-it-used-their-flickr-photos-for-facial-recognition-training

**Comment by ThomasTJdev** [comment]
Closing
