### ISSUE TITLE
ORM Swap

### ISSUE THREAD

**Issue by juancarlospaco** [ThomasTJdev/nim_websitecreator#55]
Today a new ORM was born:
https://github.com/moigagoo/norm#norm-a-nim-orm
https://nimble.directory/pkg/norm

Its better than Gatabase:
https://github.com/juancarlospaco/nim-gatabase

Tentative plans:
- [x] Remove Gatabase.
- [ ] Add Norm.
- [x] Deprecate Gatabase.
- [x] If anything good to salvage from Gatabase send Pull Request to Norm.
- [x] Remove Gatabase from Nimble.

Norm criticism:
- Seems Undocumented?, [but have examples.](https://github.com/moigagoo/norm/blob/develop/tests/testpostgres.nim)
- Depends on Chronicles, but is maintained by Nimbus.

Gatabase criticism:
- Gatabase is stalled (with all coding going to Nimwc) offers no better features than Norm anyways.

Sorry about the all the noise but having no ORM from the start was a hard time, but I feel is something we MUST have.

**Comment by ThomasTJdev** [comment]
Hi @juancarlospaco 

I'm in for staying and using pure SQL. Otherwise we could use https://github.com/ThomasTJdev/nim_sqlbuilder to ease the writing of SQL queries.

**Comment by juancarlospaco** [comment]
I like `nim_sqlbuilder` very much. :+1: 

I was wondering if we can make like a mix between `gatabase` and `nim_sqlbuilder`,
like [Gatabase providing the UX](https://github.com/juancarlospaco/nim-gatabase#support) for the end user and `nim_sqlbuilder` actually doing the job in the back. 
Gatabase [uses pure SQL](https://github.com/juancarlospaco/nim-gatabase/blob/master/examples/minimal.nim), just adds a comfortable DSL, the benefit is that DSL is almost valid SQL,
then you can use any SQL WYSIWYG editor and copy over the SQL into the DSL, or write SQL.
:thinking:
