### ISSUE TITLE
Specify custom filename 

### ISSUE THREAD

**Issue by ThomasTJdev** [ThomasTJdev/nim_websitecreator#64]
Specify the filename in the `config.cfg` and compile with `nim c -o:customFilename nimwc`.

This will allow the user to have multiple instance running and not having all named `nimwc`.

**Comment by juancarlospaco** [comment]
`appname = ""`
So that can be reused on several places including Plugins. It can use a random string if left blank.
:thinking:

**Comment by ThomasTJdev** [comment]
Agree 👍. Let's insert "nimwc" as standard? Maybe blank should not be accepted?

**Comment by juancarlospaco** [comment]
I agree :+1:
