### ISSUE TITLE
Error: Xvfb program was not found

### ISSUE THREAD

**Issue by jots** [ThomasTJdev/nim_websitecreator#68]
running ./nimwc gives:
Error: Xvfb program was not found in /usr/bin directory, please install it

I have noX=true in config.cfg in the firejail section.

Why does it want Xvfb?

**Comment by juancarlospaco** [comment]
X Isolation.

You have 2 options, Install it or Disable it `noX=false`.
Usually is named `xorg-server-xvfb` or `xvfb` on most Linux distros.
:slightly_smiling_face:

**Comment by jots** [comment]
Thank you!  I had that option backwards in my mind.
Now I get:
```
Mounting tmpfs on /var/lock
Error mounting /lock: fs_var.c:254 fs_var_lock: Too many levels of symbolic links
Error: proc 4901 cannot sync with peer: unexpected EOF
Peer 4902 unexpectedly exited with status 1
```
I'm running this on crouton on a chromebook.
Is this another firejail problem?  
How can I disable firejail?
I tried `nim c -d:firejail=no nimwc.nim` but that didnt' do it.

**Comment by juancarlospaco** [comment]
Just remove the `-d:firejail` from the compile command.
Then is Disabled and no Firejail code is on the binary.
Everything Firejail is also gone, including its UI.

You can also set everything to `false` on the `config.cfg`

```ini

[firejail]
noDvd=false
noSound=false
noAutoPulse=false
no3d=false
noX=false
noVideo=false
noDbus=false
noDebuggers=false
noMachineId=false
noRoot=false
noAllusers=false
noU2f=false
privateTmp=false
privateCache=false
privateDev=false
noShell=false
forceEnUsUtf8=false
caps=false
seccomp=false
noTv=false
writables=false
noMnt=false
maxSubProcesses=0
maxOpenFiles=0
maxFileSize=0
maxPendingSignals=0
timeout=0
maxCpu=0
maxRam=0
cpuCoresByNumber=0
hostsFile=/etc/hosts
dns0=""
dns1=""
dns2=""
dns3=""

```

**Comment by jots** [comment]
Thanks.  I commented out -d:firejail from nimwc.nim.cfg  and it works!
I look forward to checking this system out, it seems very cool!
