### ISSUE TITLE
`-d:demo` does only reset DB 1 time

### ISSUE THREAD

**Issue by ThomasTJdev** [ThomasTJdev/nim_websitecreator#69]
The `resetDB()` is missing a loop which means, that the DB is only reset 1 time. A `while loop` is needed:

https://github.com/ThomasTJdev/nim_websitecreator/blob/8e9a96a431b8baa01d179276d14eb38ba14354f9/nimwcpkg/nimwc_main.nim#L444-L454

**Comment by juancarlospaco** [comment]
The latest Firejail config allows a `timeout` on Hours, from `1` to `99` Hours, it works,
maybe we can just delete all that code, and use firejail to restart every `1` Hour and do a wipe.

On `config.cfg`:
```ini
[firejail]
timeout = 1
```

:slightly_smiling_face:

**Comment by ThomasTJdev** [comment]
How does the firejail reset work?
1. Is it `nimwc` or `nimwc_main` which is reset?
2. I'm running NimWC with systemctl with an auto respawn param, will that cause any conflict? 
3. If I'm running multiple NimWC instances, and NimWC-demo uses `noMnt`, would the reset increase the risk for race conditions?

**Comment by juancarlospaco** [comment]
1. `nimwc_main`
2. No, I dont think so, It does not alter that.
3. No, I dont think so, It does not alter that.

`nimwc_main` is stopped by Firejail, then `nimwc` starts it again, then cycle repeats.
:slightly_smiling_face:

**Comment by ThomasTJdev** [comment]
Testing in progress - 1 hour left ;) . When we integrate firejail more into NimWC, I think we should move the used config's to top and add comments. E.g.:

```config
timeout=0               # Will kill program after n-hour
noX=true                # If you are running headless, set it to false
noMnt=true              # Deny access to e.g. /mnt
noDvd=true
noSound=true
noAutoPulse=true
no3d=true
noVideo=true

...
```

**Comment by juancarlospaco** [comment]
The config is "position agnostic", so yeah you can move them around freely, as lon as they are under the same section, it just works.
:+1:

**Comment by ThomasTJdev** [comment]
Ok if we comment and move timeout to top in config.
