### ISSUE TITLE
nimble install nimwc   fails

### ISSUE THREAD

**Issue by qqtop** [ThomasTJdev/nim_websitecreator#70]
Using latest nim devel it fails on both the stable and head install

```
nimwc_main.nim(130, 16) template/generic instantiation of `extensionImport` from here
nimwc_main.nim(111, 5) Error: cannot generate VM code for pluginsPath = []
 Compile Error
```

**Comment by juancarlospaco** [comment]
`{.compileTime.}` is deprecated in favor of `static:` blocks.
I think, but can be something else too, devel is kinda a moving target.

**Comment by juancarlospaco** [comment]
I tracked down the problem and it seems related to https://github.com/dom96/jester/issues/188#issue-416463541
Please use Stable, or wait for Jester improvements.

**Comment by juancarlospaco** [comment]
So, we concluded that Stable Nim should be used for a Stable user experience.
