### ISSUE TITLE
Update www.nimwc.org with features, plugins, etc.

### ISSUE THREAD

**Issue by ThomasTJdev** [ThomasTJdev/nim_websitecreator#76]
I would like to update www.nimwc.org with some more info.  

**Suggestions:**

## 1) Features
Add a new page with features - copy'paste the best from the `README`

## 2) Plugin
Add a new page with the plugins. Currently we list some of the plugins in the `README` in https://github.com/ThomasTJdev/nimwc_plugins which is bad practice. That repo's `README` is not for listing the plugins. 

I suggest we make a `proc()` which grabs the updated plugins.json and generates a page with the plugins. NimWC with `-d:demo` is restarting every hour, so the plugin page would be updated often.

## 3) Reset
We'll change the reset procedure to not deleting the header, navbar and footer (standarddata), since the demo can't edit this. So instead we just hardcode the sql queries which delete demo changes - which is pages and blog posts.

@juancarlospaco

**Comment by juancarlospaco** [comment]
Anything to optimize the Reset is welcome. 
Demo is a Demo and most users have no problem understanding that from what Ive observed.

We can just list the Plugins on a `<details>` on the Features page.
:+1:
