### ISSUE TITLE
Update GitHub repo Tags

### ISSUE THREAD

**Issue by juancarlospaco** [ThomasTJdev/nim_websitecreator#82]
@ThomasTJdev you should update the GitHub repo Tags, 
to reflect more the actual features the project has nowadays, 
and add as much features as possible to the tags, it helps the project appear on GitHub searches.
I can not do it, that option is not visible for me.
Some Tags can be:

- Firejail
- 2 Factor Authentication
- WebP
- Material Design
- Bulma
- Gravatar
- Libravatar
- Recaptcha
- Web Framework
- BCrypt
- TOTP

Feel free to suggest and use more...
:slightly_smiling_face:

**Comment by ThomasTJdev** [comment]
Updated with suggestion. Let me know if you like other tags.

**Comment by juancarlospaco** [comment]
Fixed.
