### ISSUE TITLE
Set url to pages from /p/page => /page

### ISSUE THREAD

**Issue by ThomasTJdev** [ThomasTJdev/nim_websitecreator#86]
Currently a regex is used on pages, and pages needs to include a `/p/` in front. It would be more beautiful if the URL was without that, e.g. website.com/faq instead of website.com/p/faq.

https://github.com/ThomasTJdev/nim_websitecreator/blob/f977bbe45eca5abea6710af04aa15193e93051f8/nimwcpkg/resources/web/routes.nim#L966-L969

**Comment by juancarlospaco** [comment]
Kinda Blocked https://github.com/ThomasTJdev/nim_websitecreator/pull/87#issuecomment-475618232

**Comment by juancarlospaco** [comment]
See https://github.com/ThomasTJdev/nim_websitecreator/pull/87#issuecomment-489006413
