### ISSUE TITLE
Automated install

### ISSUE THREAD

**Issue by ThomasTJdev** [ThomasTJdev/nim_websitecreator#92]
Make an automated install and update for the user.

WIP: https://gist.github.com/ThomasTJdev/2110b891b4620c5f3c9635ccc52db5ad

Goal: `curl -sSL https://nimwc.org/install.sh | bash`

**Comment by juancarlospaco** [comment]
So it does not install Nim, so the user must have Nim already installed previously, 
...then why not use NimScript instead of Bash :grey_question: 
:thinking:

**Comment by ThomasTJdev** [comment]
Yeah, otherwise user will be prompted for installing using choosenim.

I just feel pretty limited using NimScript.. would it be possible to achieve the same using NimScript?

**Comment by juancarlospaco** [comment]
We can steal ideas and inspiration from https://github.com/kaushalmodi/nim_config#list-available-tasks
`nim_config` does complex stuff.

Besides Bash while being kinda universal, its features are not, 
Centos and debian stable tend to have very old bash with missing features and commands compared to newer ones.

We can try doing both too. 
It should live on the DevOps folder.
:thinking:
